// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

type IDAddressAndStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDAddressAndStatus) Reset() {
	*x = IDAddressAndStatus{}
	mi := &file_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDAddressAndStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDAddressAndStatus) ProtoMessage() {}

func (x *IDAddressAndStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDAddressAndStatus.ProtoReflect.Descriptor instead.
func (*IDAddressAndStatus) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *IDAddressAndStatus) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IDAddressAndStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IDAddressAndStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type IDAddressAndStatusList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerList    []*IDAddressAndStatus  `protobuf:"bytes,1,rep,name=serverList,proto3" json:"serverList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDAddressAndStatusList) Reset() {
	*x = IDAddressAndStatusList{}
	mi := &file_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDAddressAndStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDAddressAndStatusList) ProtoMessage() {}

func (x *IDAddressAndStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDAddressAndStatusList.ProtoReflect.Descriptor instead.
func (*IDAddressAndStatusList) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *IDAddressAndStatusList) GetServerList() []*IDAddressAndStatus {
	if x != nil {
		return x.ServerList
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{3}
}

type TimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRequest) Reset() {
	*x = TimeRequest{}
	mi := &file_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRequest) ProtoMessage() {}

func (x *TimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRequest.ProtoReflect.Descriptor instead.
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *TimeRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type ServersInformationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumServers      int64                  `protobuf:"varint,1,opt,name=numServers,proto3" json:"numServers,omitempty"`
	NumOnServers    int64                  `protobuf:"varint,2,opt,name=numOnServers,proto3" json:"numOnServers,omitempty"`
	NumOffServers   int64                  `protobuf:"varint,3,opt,name=numOffServers,proto3" json:"numOffServers,omitempty"`
	MeanUpTimeRatio float64                `protobuf:"fixed64,4,opt,name=meanUpTimeRatio,proto3" json:"meanUpTimeRatio,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServersInformationResponse) Reset() {
	*x = ServersInformationResponse{}
	mi := &file_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersInformationResponse) ProtoMessage() {}

func (x *ServersInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersInformationResponse.ProtoReflect.Descriptor instead.
func (*ServersInformationResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *ServersInformationResponse) GetNumServers() int64 {
	if x != nil {
		return x.NumServers
	}
	return 0
}

func (x *ServersInformationResponse) GetNumOnServers() int64 {
	if x != nil {
		return x.NumOnServers
	}
	return 0
}

func (x *ServersInformationResponse) GetNumOffServers() int64 {
	if x != nil {
		return x.NumOffServers
	}
	return 0
}

func (x *ServersInformationResponse) GetMeanUpTimeRatio() float64 {
	if x != nil {
		return x.MeanUpTimeRatio
	}
	return 0
}

var File_proto_server_proto protoreflect.FileDescriptor

const file_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x12proto/server.proto\x12\fmail_service\"\x0e\n" +
	"\fEmptyRequest\"V\n" +
	"\x12IDAddressAndStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"Z\n" +
	"\x16IDAddressAndStatusList\x12@\n" +
	"\n" +
	"serverList\x18\x01 \x03(\v2 .mail_service.IDAddressAndStatusR\n" +
	"serverList\"\x0f\n" +
	"\rEmptyResponse\"E\n" +
	"\vTimeRequest\x12\x1c\n" +
	"\tstartTime\x18\x01 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x02 \x01(\tR\aendTime\"\xb0\x01\n" +
	"\x1aServersInformationResponse\x12\x1e\n" +
	"\n" +
	"numServers\x18\x01 \x01(\x03R\n" +
	"numServers\x12\"\n" +
	"\fnumOnServers\x18\x02 \x01(\x03R\fnumOnServers\x12$\n" +
	"\rnumOffServers\x18\x03 \x01(\x03R\rnumOffServers\x12(\n" +
	"\x0fmeanUpTimeRatio\x18\x04 \x01(\x01R\x0fmeanUpTimeRatio2\xd4\x01\n" +
	"\x1bServerAdministrationService\x12W\n" +
	"\x13GetAddressAndStatus\x12\x1a.mail_service.EmptyRequest\x1a$.mail_service.IDAddressAndStatusList\x12\\\n" +
	"\x15GetServersInformation\x12\x19.mail_service.TimeRequest\x1a(.mail_service.ServersInformationResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData []byte
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)))
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_server_proto_goTypes = []any{
	(*EmptyRequest)(nil),               // 0: mail_service.EmptyRequest
	(*IDAddressAndStatus)(nil),         // 1: mail_service.IDAddressAndStatus
	(*IDAddressAndStatusList)(nil),     // 2: mail_service.IDAddressAndStatusList
	(*EmptyResponse)(nil),              // 3: mail_service.EmptyResponse
	(*TimeRequest)(nil),                // 4: mail_service.TimeRequest
	(*ServersInformationResponse)(nil), // 5: mail_service.ServersInformationResponse
}
var file_proto_server_proto_depIdxs = []int32{
	1, // 0: mail_service.IDAddressAndStatusList.serverList:type_name -> mail_service.IDAddressAndStatus
	0, // 1: mail_service.ServerAdministrationService.GetAddressAndStatus:input_type -> mail_service.EmptyRequest
	4, // 2: mail_service.ServerAdministrationService.GetServersInformation:input_type -> mail_service.TimeRequest
	2, // 3: mail_service.ServerAdministrationService.GetAddressAndStatus:output_type -> mail_service.IDAddressAndStatusList
	5, // 4: mail_service.ServerAdministrationService.GetServersInformation:output_type -> mail_service.ServersInformationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}
