services:
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_CONFIG_URL=/swagger-config.yaml
    volumes:
      - ./docs:/usr/share/nginx/html/docs
      - ./swagger-config.yaml:/usr/share/nginx/html/swagger-config.yaml
    network_mode: host

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    network_mode: host
  
  redis:
    image: redis:latest
    network_mode: host

  elasticsearch:
    image: elasticsearch:9.0.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    network_mode: host
  
  kibana:
    image: kibana:9.0.2
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    network_mode: host