apiVersion: v1
kind: Pod
metadata:
  namespace: vcs-sms
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
      env:
        - name: xpack.security.enabled
          value: "false"
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
      ports:
        - containerPort: 9200