services:
  healthcheck_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: healthcheck_service:latest
    environment:
      - RUNNING_ENVIRONMENT=local
    volumes:
      - .:/app
    network_mode: host