apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vcs-sms
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: mail_service
          imagePullPolicy: Never
          env:
            - name: GRPC_SERVER_ADMINISTRATION_SERVER
              value: "server-administration-service"
            - name: MAIL_SERVICE_PORT
              value: "10003"
          ports:
            - containerPort: 10003