openapi: 3.1.0
info:
  title: Mail service's APIs
  description: APIs for sending emails
  version: 1.0.0
servers:
  - url: http://localhost:10003
    description: Local mail server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /send:
    post:
      summary: Send email manually
      description: Sends an email to the specified recipient.
      security:
      - bearerAuth: []
      parameters:
        - name: start_time
          in: query
          required: true
          description: The start time for filtering emails
          schema:
            type: string
            example: 2025-06-24T00:00:00Z
        - name: end_time
          in: query
          required: true
          description: The end time for filtering emails
          schema:
            type: string
            example: 2025-06-24T23:59:59Z
        - name: to
          in: query
          required: true
          description: The email receiver
          schema:
            type: string
            example: abc@gmail.com
      responses:
        '200':
          description: Email sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email sent successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email data
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error