openapi: 3.1.0
info:
  title: User Service API
  description: API for managing users
  version: 1.0.0
servers:
  - url: http://localhost:10001
    description: Local user server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /create:
    post:
      summary: Create a new user
      description: Creates a new user with the provided details.
      security:
      - bearerAuth: []
      requestBody:
        description: User information
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: password123
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: abc123@gmail.com
                role:
                  type: string
                  enum: [sudo, admin, user]
                  example: user
              required:
                - username
                - password
                - name
                - role
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
                  userID:
                    type: string
                    example: 12345
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /login:
    post:
      summary: User login
      description: Authenticates a user and returns a token.
      requestBody:
        description: User login credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: password123
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: abcdef1234567890
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid username or password
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /getUserByID:
    get:
      summary: Get user by ID
      description: Retrieves user information based on the provided user ID.
      security:
      - bearerAuth: []
      parameters:
        - name: userID
          in: query
          required: true
          description: The ID of the user to retrieve
          schema:
            type: string
            example: 12345
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                    example: 12345
                  username:
                    type: string
                    example: johndoe
                  name:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    format: email
                    example:
                  role:
                    type: string
                    enum: [sudo, admin, user]
                    example: user
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /getAllUsers:
    get:
      summary: Get all users
      description: Retrieves a list of all users.
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userID:
                      type: string
                      example: 12345
                    username:
                      type: string
                      example: johndoe
                    name:
                      type: string
                      example: John Doe
                    email:
                      type: string
                      format: email
                      example:
                    role:
                      type: string
                      enum: [sudo, admin, user]
                      example: user
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error