apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: vcs-sms
  name: healthcheck-service
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: healthcheck-service
              image: flashhhhh/healthcheck_service:v2.0.2
              imagePullPolicy: IfNotPresent
              env:
                - name: GRPC_SERVER_ADMINISTRATION_SERVER
                  value: server-administration-service
                - name: KAFKA_HOST
                  value: kafka
                - name: KAFKA_PORT
                  value: "9092"
          restartPolicy: OnFailure
