services:
  server_administration_service:
    build:
      context: .
      dockerfile: local.Dockerfile
    image: local_server_administration_service:latest
    environment:
      - RUNNING_ENVIRONMENT=local
    ports:
      - 10002:10002
    volumes:
      - .:/app
    networks:
      - vcs-sms-network

networks:
  vcs-sms-network:
    external: true
    name: vcs-sms-network